"""Public API for deterministic figure detection."""

from projectkoios.ingestion.figures.contracts import (
    FIGURE_CONTRACT_VERSION,
    FIGURE_DETECTOR_VERSION,
    FIGURE_INSPECTOR_VERSION,
    DeterministicFigureCandidateDetector,
    EmbeddedFigureArtifact,
    FigureArtifactKind,
    FigureAssociationRole,
    FigureCandidate,
    FigureCandidateDetector,
    FigureComponent,
    FigureDetectionConfiguration,
    FigureDetectionInput,
    FigureDetectionLimitError,
    FigureDetectionResult,
    FigureDrawingEvidence,
    FigureEvidenceStatus,
    FigurePageEvidence,
    FigureTextAssociation,
    PyMuPdfFigureInspector,
)

__all__ = [
    "FIGURE_CONTRACT_VERSION",
    "FIGURE_DETECTOR_VERSION",
    "FIGURE_INSPECTOR_VERSION",
    "DeterministicFigureCandidateDetector",
    "EmbeddedFigureArtifact",
    "FigureArtifactKind",
    "FigureAssociationRole",
    "FigureCandidate",
    "FigureCandidateDetector",
    "FigureComponent",
    "FigureDetectionConfiguration",
    "FigureDetectionInput",
    "FigureDetectionLimitError",
    "FigureDetectionResult",
    "FigureDrawingEvidence",
    "FigureEvidenceStatus",
    "FigurePageEvidence",
    "FigureTextAssociation",
    "PyMuPdfFigureInspector",
]
