"""Closed reading evidence identity roles."""

from enum import StrEnum


class ReadingEvidenceIdentityKind(StrEnum):
    """Semantic roles carried by bounded reading evidence identities."""

    ASSEMBLY = "assembly"
    ASSOCIATION = "association"
    BLOCK = "block"
    CANDIDATE = "candidate"
    CAPTION = "caption"
    CLEAN_TEXT = "clean_text"
    CLEAN_TEXT_PRODUCTION = "clean_text_production"
    CLEAN_TRANSCRIPT = "clean_transcript"
    COMPOSITION = "composition"
    DOCUMENT = "document"
    DOCUMENT_PRODUCER = "document_producer"
    EVIDENCE_DOCUMENT = "evidence_document"
    EVIDENCE_INVENTORY = "evidence_inventory"
    EVIDENCE_PAGE = "evidence_page"
    EQUATION = "equation"
    EXTRACTION_RESULT = "extraction_result"
    FIGURE = "figure"
    LIMITATION = "limitation"
    LINEAGE = "lineage"
    OCR_RESULT = "ocr_result"
    PAGE_LOCATION = "page_location"
    PAGE_TEXT = "page_text"
    PRODUCER = "producer"
    PRODUCER_LINEAGE = "producer_lineage"
    PROJECTION_CONFIGURATION = "projection_configuration"
    PROJECTION_REQUEST = "projection_request"
    PROJECTION_RESULT = "projection_result"
    RECONCILIATION = "reconciliation"
    REGION = "region"
    SOURCE = "source"
    SOURCE_BLOCK = "source_block"
    SOURCE_OBJECT = "source_object"
    SOURCE_SPAN = "source_span"
    STRUCTURED_ITEM = "structured_item"
    STRUCTURED_ITEM_PRODUCTION = "structured_item_production"
    STRUCTURED_TRANSCRIPTION = "structured_transcription"
    TABLE = "table"
    TEXT_SELECTION = "text_selection"
    TEXT_STREAM = "text_stream"
    TRANSFORMATION = "transformation"
    VISUAL_ASSESSMENT = "visual_assessment"
    WARNING = "warning"
