"""OCR domain contracts and nominal bases."""

from projectkoios.ingestion.ocr.base import OCRTextOutput
from projectkoios.ingestion.ocr.contracts import (
    OCR_CONTRACT_VERSION,
    PIXEL_COORDINATE_SYSTEM,
    OCRConfidence,
    OCRConfiguration,
    OCRContractLimitError,
    OCRFailure,
    OCRFailureKind,
    OCRLanguageResourceIdentity,
    OCRLine,
    OCRNativeTextBlockReference,
    OCROutputMode,
    OCRPageImage,
    OCRProcessorIdentity,
    OCRRequest,
    OCRResourceIdentityKind,
    OCRResult,
    OCRResultStatus,
    OCRSelection,
    OCRSelectionResult,
    OCRSelectionStatus,
    OCRToken,
    OCRWarning,
    build_ocr_cache_key,
)

_PUBLIC_TYPES = (
    OCRConfidence,
    OCRConfiguration,
    OCRContractLimitError,
    OCRFailure,
    OCRFailureKind,
    OCRLanguageResourceIdentity,
    OCRLine,
    OCRNativeTextBlockReference,
    OCROutputMode,
    OCRPageImage,
    OCRProcessorIdentity,
    OCRRequest,
    OCRResourceIdentityKind,
    OCRResult,
    OCRResultStatus,
    OCRSelection,
    OCRSelectionResult,
    OCRSelectionStatus,
    OCRToken,
    OCRWarning,
)
for _public_type in _PUBLIC_TYPES:
    _public_type.__module__ = __name__
del _public_type

__all__ = [
    "OCR_CONTRACT_VERSION",
    "PIXEL_COORDINATE_SYSTEM",
    "OCRConfidence",
    "OCRConfiguration",
    "OCRContractLimitError",
    "OCRFailure",
    "OCRFailureKind",
    "OCRLanguageResourceIdentity",
    "OCRLine",
    "OCRNativeTextBlockReference",
    "OCROutputMode",
    "OCRPageImage",
    "OCRProcessorIdentity",
    "OCRRequest",
    "OCRResourceIdentityKind",
    "OCRResult",
    "OCRResultStatus",
    "OCRSelection",
    "OCRSelectionResult",
    "OCRSelectionStatus",
    "OCRTextOutput",
    "OCRToken",
    "OCRWarning",
    "build_ocr_cache_key",
]
