"""Hard limits for LayoutParser detection adaptation."""

MAX_LAYOUT_PARSER_LABEL_MAPPINGS = 256
MAX_LAYOUT_PARSER_LABEL_CHARACTERS = 256
MAX_LAYOUT_PARSER_LABEL_MAPPING_CHARACTERS = 16_384
MAX_LAYOUT_PARSER_DETECTION_LABEL_CHARACTERS = 262_144
