"""Hard bounds for reference page location."""

REFERENCE_LOCATOR_MAX_ANCHORS = 32
REFERENCE_LOCATOR_MAX_ANCHOR_CHARACTERS = 256
REFERENCE_LOCATOR_MAX_ANCHOR_TOKENS = 32
REFERENCE_LOCATOR_MAX_PAGE_CHARACTERS = 2_000_000
