"""Hard COCO layout-adaptation implementation limits."""

from projectkoios.ingestion.layout.proposal.limits.definition import (
    MAX_LAYOUT_REGION_PROPOSALS,
)

MAX_COCO_LAYOUT_CATEGORIES = 256
MAX_COCO_LAYOUT_CATEGORY_NAME_CHARACTERS = 128
MAX_COCO_LAYOUT_CATEGORY_NAME_TOTAL_CHARACTERS = 8_192
MAX_COCO_LAYOUT_IMAGES = 5_000
MAX_COCO_LAYOUT_DETECTIONS = MAX_LAYOUT_REGION_PROPOSALS
MAX_COCO_LAYOUT_JSON_BYTES = 16 * 1024 * 1024
MAX_COCO_LAYOUT_JSON_CONTAINER_DEPTH = 12
MAX_COCO_LAYOUT_JSON_ITEMS = 100_000
MAX_COCO_LAYOUT_JSON_NUMBER_CHARACTERS = 64
MAX_COCO_LAYOUT_JSON_STRING_BYTES = 8_192
MAX_COCO_LAYOUT_JSON_TOTAL_STRING_BYTES = 2 * 1024 * 1024
