"""Public API for deterministic table detection."""

from projectkoios.ingestion.tables.contracts import (
    TABLE_CONTRACT_VERSION,
    TABLE_DETECTOR_VERSION,
    TABLE_RULE_INSPECTOR_VERSION,
    DeterministicTableCandidateDetector,
    PyMuPdfTableRuleInspector,
    TableAssociationRole,
    TableBoundaryKind,
    TableCandidate,
    TableCandidateDetector,
    TableDetectionConfiguration,
    TableDetectionInput,
    TableDetectionLimitError,
    TableDetectionResult,
    TableEvidenceStatus,
    TablePageRuleEvidence,
    TableRegionEvidence,
    TableRuleInspector,
    TableRuleOrientation,
    TableRuleSegment,
    TableTextAssociation,
)
from projectkoios.ingestion.tables.contracts import (
    _axis_segments as _axis_segments,
)

__all__ = [
    "TABLE_CONTRACT_VERSION",
    "TABLE_DETECTOR_VERSION",
    "TABLE_RULE_INSPECTOR_VERSION",
    "DeterministicTableCandidateDetector",
    "PyMuPdfTableRuleInspector",
    "TableAssociationRole",
    "TableBoundaryKind",
    "TableCandidate",
    "TableCandidateDetector",
    "TableDetectionConfiguration",
    "TableDetectionInput",
    "TableDetectionLimitError",
    "TableDetectionResult",
    "TableEvidenceStatus",
    "TablePageRuleEvidence",
    "TableRegionEvidence",
    "TableRuleInspector",
    "TableRuleOrientation",
    "TableRuleSegment",
    "TableTextAssociation",
]
